### ISSUE TITLE
When deleting politician, there is 400 error

### ISSUE THREAD

**Issue by kollermartin** [Politi-cz/politicz-politicians-and-parties#1]
### **Steps to reproduce**
1. Select politician and click on delete action in quick menu

![Image](https://user-images.githubusercontent.com/51463346/222960381-9ec493c7-d88e-488c-b268-39eb95717729.png)

### **Behavior**
I receive 400 error

![Image](https://user-images.githubusercontent.com/51463346/222960461-df2f0e17-2844-46d2-b3fe-115a1164a616.png)

![Image](https://user-images.githubusercontent.com/51463346/222960495-fc3d2256-d5a8-4885-a26a-47a04a100d2b.png)

### **Expected behavior**
Politician is deleted

**Comment by PetrKoller** [comment]
You are calling wrong endpoint. Trying to delete a politician through political parties api
